"""empty message

Revision ID: 5ec61067dafe
Revises: db82ada6a31a
Create Date: 2022-04-09 16:17:27.873727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ec61067dafe'
down_revision = 'db82ada6a31a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_name', sa.String(length=150), nullable=False))
    op.add_column('book', sa.Column('published_year', sa.String(length=255), nullable=True))
    op.drop_column('book', 'image')
    op.drop_column('book', 'price')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('book', 'published_year')
    op.drop_column('book', 'author_name')
    # ### end Alembic commands ###
