"""empty message

Revision ID: 2edc56a96e7b
Revises: b2eab82e3f6f
Create Date: 2022-04-08 03:26:40.894552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2edc56a96e7b'
down_revision = 'b2eab82e3f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('booking_details', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.String(length=500), nullable=False),
    sa.Column('date_of_booking', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_classroom_invitee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_classroom_invitee')
    op.drop_table('virtual_classroom')
    # ### end Alembic commands ###
