"""empty message

Revision ID: 4c4b691cf335
Revises: a83fafd652a9
Create Date: 2022-04-09 01:31:25.462895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c4b691cf335'
down_revision = 'a83fafd652a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('meeting_information', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.String(length=500), nullable=False),
    sa.Column('date_of_booking', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_classroom_invitee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.String(length=100), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['virtual_classroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_classroom_invitee')
    op.drop_table('virtual_classroom')
    # ### end Alembic commands ###
