"""empty message

Revision ID: d069eaae95d8
Revises: 8ca2c7243930
Create Date: 2022-04-08 03:16:46.519991

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd069eaae95d8'
down_revision = '8ca2c7243930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.String(length=400), nullable=False),
    sa.Column('booking_details', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.String(length=500), nullable=False),
    sa.Column('date_of_booking', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_classroom_invitee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('classroom_booking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_booking',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.VARCHAR(length=400), autoincrement=False, nullable=False),
    sa.Column('book_details', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('date_of_booking', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='classroom_booking_pkey')
    )
    op.drop_table('virtual_classroom_invitee')
    op.drop_table('virtual_classroom')
    # ### end Alembic commands ###
