"""empty message

Revision ID: dd7960137602
Revises: 55868812c0db
Create Date: 2022-04-08 03:46:25.306314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7960137602'
down_revision = '55868812c0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('virtual_classroom',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('meeting_information', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.String(length=500), nullable=False),
    sa.Column('date_of_booking', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('virtual_classroom_invitee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invitee_id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['virtual_classroom.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('virtual_classroom_invitee')
    op.drop_table('virtual_classroom')
    # ### end Alembic commands ###
